name: destroy development

on:
  push:
    # branches:
    #   - main
    tags:
      - 'destroy-dev-*'
  # pull_request:

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup AWS CLI for "gh actions" user
        id: ghactions
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::464919712823:role/admin-role-gh-actions
          role-duration-seconds: 1200
          role-session-name: GithubActionsSession

      - name: Get Terraform Version
        run: |
          echo "TF_VERSION=$(head -n 1 .terraform-version)" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          # terraform_version: 1.3.4
          terraform_version: $TF_VERSION

      - name: Terraform Init
        id: init
        run: terraform init

      # validates the configuration files in a directory, referring only to the configuration 
      # and not accessing any remote services such as remote state, provider APIs, etc.
      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Destroy
        id: destroy
        if: steps.validate.outcome == 'success'
        run: |
          terraform destroy -auto-approve
        
      - name: Delete All Releases
        id: releases-delete
        if: steps.destroy.outcome == 'success'
        run: |
          gh release list | awk '{print $1;}' | xargs -L1 gh release delete
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
